### ISSUE TITLE
Docs: Add GitHub learning lab

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/starter-kit#10]
What do you think? Create a folder named `GitHub-Lab` for GitHub learning lab or add it to the `starter-kit` folder?

**Comment by Evavic44** [comment]
Sorry but to be clear, do you mean the resources folder where the starter-kit lives?

**Comment by vinzvinci** [comment]
I uh... I mean put it on `resources folder` not ~~starter-kit~~ folder `(there's no starter-kit folder)`

Hmm but I think it's better to create `GitHub` folder for that.

**Comment by Rahma-AlWadhahi** [comment]
> I uh... I mean put it on `resources folder` not ~starter-kit~ folder `(there's no starter-kit folder)`
> 
> Hmm but I think it's better to create `GitHub` folder for that.

I don’t think that there is a need to create a folder. GitHub learning lab could be added as a link in the readme with some description. Related to #5 

@Evavic44 if you want to take this, here is the link to GitHub learning lab
https://lab.github.com/

**Comment by vinzvinci** [comment]
Yeah I think better add that on the `README`. Thank you @Rahma-AlWadhahi :+1:

**Comment by Evavic44** [comment]
> > I uh... I mean put it on `resources folder` not ~starter-kit~ folder `(there's no starter-kit folder)`
> > Hmm but I think it's better to create `GitHub` folder for that.
> 
> I don’t think that there is a need to create a folder. GitHub learning lab could be added as a link in the readme with some description. Related to #5
> 
> @Evavic44 if you want to take this, here is the link to GitHub learning lab
> https://lab.github.com/

Okay. Will do that. Thanks.

**Comment by Evavic44** [comment]
> Yeah I think better add that on the `README`. Thank you @Rahma-AlWadhahi 👍

I've added it.

**Comment by vinzvinci** [comment]
Thank you @Evavic44, hmm but before I merge it. Do you think it's better to make it number 1 in the free course list?

**Comment by vinzvinci** [comment]
Hey @Evavic44, I merged it. Thanks

**Comment by Evavic44** [comment]
You're welcome. Thanks
