### ISSUE TITLE
need (docs): good-first-issue website

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/starter-kit#17]
Hello folks, if there's any website that has a different category for every language that offers `good-first-issue`, feel free to share it here and update the content of <a href="https://github.com/SurPathHub/starter-kit/blob/main/practice/open-source-practice.md">open-source-practice.md</a>.

**Comment by slayer321** [comment]
Hey @vinzvinci, I know some website that offers `good first issue` on the bases of programming language that I can add to this .md file.
I will like to take this issue.

**Comment by vinzvinci** [comment]
Okay just put it there, don't remove those content.

**Comment by vinzvinci** [comment]
Thank you @slayer321 - #21 merged 👍
