### ISSUE TITLE
feat: Add typo mistake templates

### ISSUE THREAD

**Issue by longqua69** [SurPathHub/starter-kit#29]
**Is your feature request related to a problem? Please describe.**
I've found some typo mistakes in the repository. Recently, there are 2 templates for bug and feature request but not typo mistake. Fixing typo mistakes is easier than filling the current templates.

**Describe the solution you'd like**
I think we should create templates for typo issue and PRs

**Describe alternatives you've considered**
Using blank issue is OK but I think we should keep consistency.

**Additional context**
Issue #27 is an example.

**Comment by vinzvinci** [comment]
Thank you for contributing, I merged your PR #27. If you found more, please feel free to contribute :)
