### ISSUE TITLE
Update GitHub Labs link

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [SurPathHub/starter-kit#41]
**Describe the bug**
The website of GitHub Labs is updated to https://skills.github.com in the doc it is not mentioned precisely.

File location: https://github.com/SurPathHub/starter-kit/blob/main/courses/free-course-list.md (Section "Special")

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/63872951/194266822-1ef6c93f-8853-42a3-88b8-3014472dc1b3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinzvinci** [comment]
I can add hacktoberfest label for this, would u be up to work with this issue?

**Comment by ShubhamJagtap2000** [comment]
> I can add hacktoberfest label for this, would u be up to work with this issue?

Yes, of course. Should I raise PR then?

**Comment by vinzvinci** [comment]
Sure!
