### ISSUE TITLE
Docs: Add more free courses

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/starter-kit#5]
Add more free courses here: <a href="https://github.com/SurPathHub/starter-kit/blob/main/courses/free-course-list.md">https://github.com/SurPathHub/starter-kit/blob/main/courses/free-course-list.md</a>

Ex.
- Link
- Provide 1 - 3 sentences.

Note: We provide quality content & a platform for the student to learn for free.

**Comment by vinzvinci** [comment]
w3schools is added #6

**Comment by vinzvinci** [comment]
TheOdinProject is added #7

**Comment by srisatya1197** [comment]
@vinzvinci can I add interview bit, SoloLearn, TutorialsPoint.

**Comment by vinzvinci** [comment]
Add SoloLearn to Free Course List @srisatya1197, that's all and I'm going to close this issue after that.

**Comment by srisatya1197** [comment]
Ok Sure.
